name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest  # or ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 23
        uses: actions/setup-java@v2
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Build and test
        run: mvn clean install

      - name: Upload JAR file
        uses: actions/upload-artifact@v2
        with:
          name: my-spring-boot-app
          path: target/*.jar
