name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 23
      uses: actions/setup-java@v2
      with:
        java-version: '23'
        distribution: 'temurin'

    - name: Build and Test with Maven
      run: mvn clean install

    - name: Run Tests
      run: mvn test
      env:
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    - name: Upload JAR file
      uses: actions/upload-artifact@v2
      with:
        name: my-spring-boot-app
        path: target/*.jar  # Adjust this if you want to specify a particular JAR file
