name: Java CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Build Project
        run: mvn clean install

      - name: Upload JAR file
        uses: actions/upload-artifact@v3
        with:
          name: springboot-app
          path: target/*.jar
