name: CI

on:
  push:
    branches:
      - main  # Change this to your default branch if it's different
  pull_request:
    branches:
      - main  # Change this to your default branch if it's different

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu for the build environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 23
      uses: actions/setup-java@v2
      with:
        java-version: '23'  # Specify Java version 23

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test
